
spring:
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: 92341899ae11a8244697
                        client-secret: 4b58e11f78a9c88a85ab5fd0f88d3bde9ba84750
                    google:
                        client-id: 194192899177-bv9a1d27cia00l8qjftab9vf18rdusaa.apps.googleusercontent.com
                        client-secret: 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